### ISSUE TITLE
MEV Research Workshop Agenda 2/4/2021

### ISSUE THREAD

**Issue by CarboClanC** [flashbots/mev-research#32]
Date: Thursday, Feb 4, 2021
Time: 11:30am PST / 2:30pm EST 
[Join Call](https://meet.google.com/bza-ebye-tow) | [Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_7lurqn12ecl64li0ms3kse5vok@group.calendar.google.com)

A discussion on auction mechanism designs for MEV auction:
1. Survey of trade-offs between auction mechanism design
2. Share update on the auction mechanism design [FRP](https://github.com/flashbots/mev-research/pull/29/files?short_path=997a936#diff-997a936f4f98d63cb411a5fab8746d1556c3806fc6ec83d51697e5d11d79f415)
2. Updates on Flashbots FRP process and new batch of MEV Fellowship

**Comment by sbaks0820** [comment]
Questions for discussion:

1. Second-price auctions are susceptible to malicious miners/auctioneers who inflate the second-price with fake bids. Should MEV-GETH opt for a first price sealed-bid auction instead so that bots know the price they pay for block space is not tampered with?
2. Will all intermediaries eventually leave so bots submit bits directly to miners? Even if intermediaries offer to collect small tx bundles into large bundles, miners would prefer to do the work themselves to ensure they are capturing all possible revenue.
3. Bot operators desire more transparency in the auction so that they can observe the strategies and bidding behavior of other agents. Although a sealed-bid second price auction provides strong theoretical guarantees of truth-telling, what tradeoff should be made to encourage adoption of MEV-GETH auctions over existing PGAs in the mempool?
